import = [
    # See https://github.com/alacritty/alacritty-theme
    "/usr/share/alacritty/themes/gruvbox_dark.toml"
]

[colors.primary]
# Use gruvbox hard background color
background = "#1d2021"

[font]
normal = { family = "Input Mono" }
size = 10
