dotfiles_dir = ".dotfiles"
gpg_user_id = "svenstaro@gmail.com"

[settings]
vars = [ "vars/base.toml" ]

[settings.dots]
btop = { source = "btop/btop.conf", target = ".config/btop/btop.conf" }

git = { source = "git/gitconfig", target = ".gitconfig" }

gnupg_agent = { source = "gnupg/gpg-agent.conf", target = ".gnupg/gpg-agent.conf" }
gnupg = { source = "gnupg/gpg.conf", target = ".gnupg/gpg.conf" }

subversion = { source = "svn/config", target = ".subversion/config" }

tmux = { source = "tmux/tmux.conf", target = ".config/tmux/tmux.conf" }
tmate = { source = "tmux/tmate.conf", target = ".tmate.conf" }

vim_coc_settings = { source = "vim/coc-settings.json", target = ".config/nvim/coc-settings.json" }
vim_init = { source = "vim/init.vim", target = ".config/nvim/init.vim" }
vim_plug = { source = "vim/plug.vim", target = ".config/nvim/autoload/plug.vim" }

zsh = { source = "zsh/zshrc", target = ".zshrc" }
zshenv = { source = "zsh/zshenv", target = ".zshenv" }

[profiles.neo]
vars = [ "vars/neo.toml" ]

[profiles.neo.dots]
dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }
fonts = { source = "fonts/fonts.conf", target = ".config/fontconfig/fonts.conf" }
gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
gtk3 = { source = "gtk/gtk3-settings.ini", target = ".config/gtk-3.0/settings.ini" }
helix = { source = "helix/config.toml", target = ".config/helix/config.toml" }
hg = { source = "hg/hgrc", target = ".hgrc" }
htop = { source = "htop/htoprc", target = "htop/.htoprc" }

i3 = { source = "i3/config", target = ".config/i3/config"}
i3_dmrc = { source = "i3/dmrc", target = ".dmrc"}
i3_status_rust = { source = "i3/i3status-rust.toml", target = ".config/i3status-rust/config.toml" }

inputrc = { source = "inputrc/inputrc", target = ".inputrc" }
makepkg = { source = "makepkg/makepkg.conf", target = ".config/pacman/makepkg.conf" }
rofi = { source = "rofi/config.rasi", target = ".config/rofi/config.rasi" }
termite = { source = "termite/config", target = ".config/termite/config" }

xinitrc = { source = "x11/xinitrc", target = ".xinitrc" }
xprofile = { source = "x11/xprofile", target = ".xprofile" }
xresources = { source = "x11/Xresources", target = ".Xresources"}

[profiles.smith]
vars = [ "vars/smith.toml" ]

[profiles.smith.dots]
dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }
fonts = { source = "fonts/fonts.conf", target = ".config/fontconfig/fonts.conf" }
gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
gtk3 = { source = "gtk/gtk3-settings.ini", target = ".config/gtk-3.0/settings.ini" }
helix = { source = "helix/config.toml", target = ".config/helix/config.toml" }
hg = { source = "hg/hgrc", target = ".hgrc" }
htop = { source = "htop/htoprc", target = "htop/.htoprc" }

i3 = { source = "i3/config", target = ".config/i3/config"}
i3_dmrc = { source = "i3/dmrc", target = ".dmrc"}
i3_status_rust = { source = "i3/i3status-rust.toml", target = ".config/i3status-rust/config.toml" }

inputrc = { source = "inputrc/inputrc", target = ".inputrc" }
makepkg = { source = "makepkg/makepkg.conf", target = ".config/pacman/makepkg.conf" }
rofi = { source = "rofi/config.rasi", target = ".config/rofi/config.rasi" }
termite = { source = "termite/config", target = ".config/termite/config" }

xinitrc = { source = "x11/xinitrc", target = ".xinitrc" }
xprofile = { source = "x11/xprofile", target = ".xprofile" }
xresources = { source = "x11/Xresources", target = ".Xresources"}

[profiles.dozer]
vars = [ "vars/dozer.toml" ]

[profiles.dozer.dots]
beets = { source = "beets/config.yaml", target = ".config/beets/config.yaml" }
beets_genres = { source = "beets/genres.txt", target = ".config/beets/genres.txt" }
