dotfiles_dir = ".dotfiles"
gpg_user_id = "svenstaro@gmail.com"

[settings]
vars = [ "vars/base.toml" ]
posthooks = [
  "systemctl --user daemon-reload",
  "systemctl --user enable dotfiles-deploy.service",
]

[settings.dots]
dotfiles_deploy_service = { source = "user-services/dotfiles-deploy.service", target = ".config/systemd/user/dotfiles-deploy.service" }

btop = { source = "btop/btop.conf", target = ".config/btop/btop.conf" }
htop = { source = "htop/htoprc", target = ".config/htop/htoprc" }

git = { source = "git/gitconfig", target = ".gitconfig" }
hg = { source = "hg/hgrc", target = ".hgrc" }
poetry = { source = "poetry/config.toml", target = ".config/poetry/config.toml" }
psql = { source = "psql/psqlrc", target = ".psqlrc" }

gnupg_agent = { source = "gnupg/gpg-agent.conf", target = ".gnupg/gpg-agent.conf" }
gnupg = { source = "gnupg/gpg.conf", target = ".gnupg/gpg.conf" }

tmux = { source = "tmux/tmux.conf", target = ".config/tmux/tmux.conf" }
tmate = { source = "tmux/tmate.conf", target = ".tmate.conf" }

helix = { source = "helix/config.toml", target = ".config/helix/config.toml" }
nvim_init = { source = "nvim/init.lua", target = ".config/nvim/init.lua" }
nvim_chadrc = { source = "nvim/lua/chadrc.lua", target = ".config/nvim/lua/chadrc.lua" }
nvim_mappings = { source = "nvim/lua/mappings.lua", target = ".config/nvim/lua/mappings.lua" }
nvim_options = { source = "nvim/lua/options.lua", target = ".config/nvim/lua/options.lua" }

nvim_plugins_init = { source = "nvim/lua/plugins/init.lua", target = ".config/nvim/lua/plugins/init.lua" }

nvim_config_codecompanion = { source = "nvim/lua/configs/codecompanion.lua", target = ".config/nvim/lua/configs/codecompanion.lua" }
nvim_config_conform = { source = "nvim/lua/configs/conform.lua", target = ".config/nvim/lua/configs/conform.lua" }
nvim_config_lazy = { source = "nvim/lua/configs/lazy.lua", target = ".config/nvim/lua/configs/lazy.lua" }
nvim_config_lspconfig = { source = "nvim/lua/configs/lspconfig.lua", target = ".config/nvim/lua/configs/lspconfig.lua" }

zsh = { source = "zsh/zshrc", target = ".zshrc" }
zshenv = { source = "zsh/zshenv", target = ".zshenv" }
starship = { source = "starship/starship.toml", target = ".config/starship.toml" }
sheldon = { source = "sheldon/plugins.toml", target = ".config/sheldon/plugins.toml" }
atuin = { source = "atuin/config.toml", target = ".config/atuin/config.toml" }

[profiles.neo]
vars = [ "vars/neo.toml" ]

[profiles.neo.dots]
fonts = { source = "fonts/fonts.conf", target = ".config/fontconfig/fonts.conf" }
gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
gtk3 = { source = "gtk/gtk3-settings.ini", target = ".config/gtk-3.0/settings.ini" }
gtk4 = { source = "gtk/gtk4-settings.ini", target = ".config/gtk-4.0/settings.ini" }

dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }
rofi = { source = "rofi/config.rasi", target = ".config/rofi/config.rasi" }
redshift = { source = "redshift/redshift.conf", target = ".config/redshift/redshift.conf" }
i3 = { source = "i3/config", target = ".config/i3/config"}
i3_dmrc = { source = "i3/dmrc", target = ".dmrc"}
i3_status_rust = { source = "i3/i3status-rust.toml", target = ".config/i3status-rust/config.toml" }
i3_workspace = { source = "i3/workspace_1.json", target = ".config/i3/workspace_1.json" }

inputrc = { source = "inputrc/inputrc", target = ".inputrc" }
makepkg = { source = "makepkg/makepkg.conf", target = ".config/pacman/makepkg.conf" }
mpv = { source = "mpv/config", target = ".config/mpv/config" }

pipewire = { source = "pipewire/fix-discord-notifications.conf", target = ".config/pipewire/pipewire-pulse.conf.d/fix-discord-notifications.conf" }

wezterm = { source = "wezterm/wezterm.lua", target = ".config/wezterm/wezterm.lua" }

xinitrc = { source = "x11/xinitrc", target = ".xinitrc" }
xprofile = { source = "x11/xprofile", target = ".xprofile" }
xresources = { source = "x11/Xresources", target = ".Xresources" }

looking_glass = { source = "looking-glass/looking-glass-client.ini", target = ".config/looking-glass/client.ini" }

[profiles.archvm]
vars = [ "vars/archvm.toml" ]

[profiles.archvm.dots]
fonts = { source = "fonts/fonts.conf", target = ".config/fontconfig/fonts.conf" }
gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
gtk3 = { source = "gtk/gtk3-settings.ini", target = ".config/gtk-3.0/settings.ini" }
gtk4 = { source = "gtk/gtk4-settings.ini", target = ".config/gtk-4.0/settings.ini" }
gtk4-css = { source = "gtk/gtk4.css", target = ".config/gtk-4.0/gtk.css" }

dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }
rofi = { source = "rofi/config.rasi", target = ".config/rofi/config.rasi" }
i3 = { source = "i3/config", target = ".config/i3/config"}
i3_dmrc = { source = "i3/dmrc", target = ".dmrc"}
i3_status_rust = { source = "i3/i3status-rust.toml", target = ".config/i3status-rust/config.toml" }

inputrc = { source = "inputrc/inputrc", target = ".inputrc" }
makepkg = { source = "makepkg/makepkg.conf", target = ".config/pacman/makepkg.conf" }
mpv = { source = "mpv/config", target = ".config/mpv/config" }

wezterm = { source = "wezterm/wezterm.lua", target = ".config/wezterm/wezterm.lua" }

xinitrc = { source = "x11/xinitrc", target = ".xinitrc" }
xprofile = { source = "x11/xprofile", target = ".xprofile" }
xresources = { source = "x11/Xresources", target = ".Xresources" }

[profiles.tank]
vars = [ "vars/tank.toml" ]

[profiles.tank.dots]

[profiles.cypher]
vars = [ "vars/cypher.toml" ]
posthooks = [
  "kitten theme --dump-theme 'Gruvbox Dark Hard' > ~/.config/kitty/current-theme.conf",
  "pkill -USR2 waybar",
  "mergiraf languages --gitattributes > ~/.gitattributes"
]

[profiles.cypher.dots]
fonts = { source = "fonts/fonts.conf", target = ".config/fontconfig/fonts.conf" }
gtk2 = { source = "gtk/gtkrc-2.0", target = ".gtkrc-2.0" }
gtk3 = { source = "gtk/gtk3-settings.ini", target = ".config/gtk-3.0/settings.ini" }
gtk4 = { source = "gtk/gtk4-settings.ini", target = ".config/gtk-4.0/settings.ini" }
gtk4-css = { source = "gtk/gtk4.css", target = ".config/gtk-4.0/gtk.css" }

makepkg = { source = "makepkg/makepkg.conf", target = ".config/pacman/makepkg.conf" }
mpv = { source = "mpv/config", target = ".config/mpv/config" }

dunst = { source = "dunst/dunstrc", target = ".config/dunst/dunstrc" }
kitty = { source = "kitty/kitty.conf", target = ".config/kitty/kitty.conf" }
rofi = { source = "rofi/config.rasi", target = ".config/rofi/config.rasi" }

hyprland = { source = "hypr/hyprland.conf", target = ".config/hypr/hyprland.conf" }
hyprland-binds = { source = "hypr/binds.conf", target = ".config/hypr/binds.conf" }
hyprland-input = { source = "hypr/input.conf", target = ".config/hypr/input.conf" }
hyprland-rules = { source = "hypr/rules.conf", target = ".config/hypr/rules.conf" }
hypridle = { source = "hypr/hypridle.conf", target = ".config/hypr/hypridle.conf" }
hyprlock-battery = { source = "hypr/battery.sh", target = ".config/hypr/battery.sh" }
hyprlock = { source = "hypr/hyprlock.conf", target = ".config/hypr/hyprlock.conf" }
xdph = { source = "hypr/xdph.conf", target = ".config/hypr/xdph.conf" }
wpaperd = { source = "wpaperd/config.toml", target = ".config/wpaperd/config.toml" }
warbar_config = { source = "waybar/config.jsonc", target = ".config/waybar/config.jsonc" }
warbar_style = { source = "waybar/style.css", target = ".config/waybar/style.css" }

aichat = { source = "aichat/config.yaml", target = ".config/aichat/config.yaml" }

[profiles.morpheus]
vars = [ "vars/morpheus.toml" ]

[profiles.morpheus.dots]
