#!/bin/bash

export QT_AUTO_SCREEN_SCALE_FACTOR=1

# We start redshift-gtk via systemd user service nowadays.
# redshift-gtk &
numlockx &
./.fehbg &
dunst &

{%- if launch_messengers == "true" %}
# Messengers
(sleep 2 && slack) &
(sleep 2 && telegram-desktop) &
(sleep 2 && discord) &
(sleep 2 && signal-desktop) &
(sleep 2 && teams-for-linux --appTitle "ELOKON" --customUserDir="/home/svenstaro/.teams-data/elokon") &
# teams-for-linux --appTitle "Personal" --customUserDir="/home/svenstaro/.teams-data/personal" &
(sleep 2 && element-desktop) &
{%- endif %}
systemctl is-enabled bluetooth && blueman-applet &

{%- if profile == "neo" %}
(sleep 5 && easyeffects --gapplication-service) &
{%- endif %}

export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/Videos/Fractals/ -type f"
export XSECURELOCK_VIDEOS_FLAGS="--panscan=1.0"
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
