#! /bin/bash

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config history_aware_focus true

bspc config auto_cancel         true
bspc config presel_feedback_color "#7373ee"

if [[ $(hostname) == 'dozer' ]]; then
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
elif [[ $(hostname) == 'smith' ]]; then
    bspc monitor VGA-0 -d I II III IV V
    bspc monitor VGA-1 -d VI VII VIII IX X
elif [[ $(hostname) == 'neo' ]]; then
    bspc monitor DVI-I-3 -d VI VII VIII IX X
    bspc monitor DVI-I-2 -d I II III IV V
fi

bspc rule -a Gimp follow=on state=floating
bspc rule -a Inkscape follow=on state=floating
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

$(dirname $0)/panel &
