#!/bin/bash

set -e
set -u

PANEL_HEIGHT=18
PANEL_PADDING=12
PANEL_FONT_FAMILY="Input Mono:style=Bold:size=8"
PANEL_ICON_FONT="Symbola:size=10"
PANEL_FIFO="/tmp/panel-fifo"

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

curdir=$(dirname $0)

[ -e "${PANEL_FIFO}" ] && rm "${PANEL_FIFO}"
mkfifo "${PANEL_FIFO}"

bspc config -m ^1 top_padding $((${PANEL_HEIGHT} + ${PANEL_PADDING}))
#bspc config -m ^1 top_padding $(($PANEL_HEIGHT + $(($PANEL_PADDING + $(bspc config border_width)))))
bspc subscribe report > "${PANEL_FIFO}" &

xtitle -sf 'T%s' > "${PANEL_FIFO}" &
${curdir}/layout.sh 'L%s' > "${PANEL_FIFO}" &
${curdir}/volume.sh 'V%s' > "${PANEL_FIFO}" &
battery -sf 'B0%s %i' -n 0 > "${PANEL_FIFO}" &
battery -sf 'B1%s %i' -n 1 > "${PANEL_FIFO}" &
${curdir}/power.sh 'P%s %hh%mm %pW' > "${PANEL_FIFO}" &
essid -sf 'E%s' -w 'wlp3s0' > "${PANEL_FIFO}" &
clock -sf 'S%a %Y-%m-%d %H:%M' > "${PANEL_FIFO}" &

screen_width=$(xrandr | grep \* | cut -d'x' -f1 | head -n1 | tr -d ' ')
panel_width=$((${screen_width} - $((${PANEL_PADDING} * 2))))

source $(dirname $0)/panel_colors

cat "${PANEL_FIFO}" | $(dirname $0)/panel_bar | lemonbar -g ${panel_width}x${PANEL_HEIGHT}+${PANEL_PADDING}+${PANEL_PADDING} -f "${PANEL_FONT_FAMILY}" -f "${PANEL_ICON_FONT}" -F "${COLOR_FOREGROUND}" -B "${COLOR_BACKGROUND}" &

wait
