#!/bin/bash

set -e

source $(dirname $0)/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        S*)
            # clock output
            clock=%{F$COLOR_INACTIVE_MONITOR_FG}⌚${F-}
            clock+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
            ;;
        T*)
            # xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            ;;
        V*)
            # volume output
            volume=%{F$COLOR_INACTIVE_MONITOR_FG}♪${F-}
            volume+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} | %{B-}%{F-}"
            ;;
        L*)
            # keyboard layout output
            layout=%{F$COLOR_INACTIVE_MONITOR_FG}⌨${F-}
            layout+="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} | %{B-}%{F-}"
            ;;
        P*)
            # power output
            power=%{F$COLOR_INACTIVE_MONITOR_FG}⚡${F-}
            power+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} | %{B-}%{F-}"
            ;;
        B*)
            # battery output
            parsed_line=${line:2}
            bat_status=${parsed_line%" "*}
            bat_capacity=${parsed_line#*" "}
            if [[ ${line:1:1} == "0" ]]; then
                battery0="%{F$COLOR_INACTIVE_MONITOR_FG}Bat0${F-}"
                if [[ ${bat_status} == "Charging" ]]; then
                    battery0+="%{F$COLOR_POSITIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                elif [[ ${bat_status} == "Discharging" ]]; then
                    battery0+="%{F$COLOR_NEGATIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                else
                    battery0+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                fi
            elif [[ ${line:1:1} == "1" ]]; then
                battery1="%{F$COLOR_INACTIVE_MONITOR_FG}Bat1${F-}"
                if [[ ${bat_status} == "Charging" ]]; then
                    battery1+="%{F$COLOR_POSITIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                elif [[ ${bat_status} == "Discharging" ]]; then
                    battery1+="%{F$COLOR_NEGATIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                else
                    battery1+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                fi
            fi
            ;;
        E*)
            # essid output
            essid=%{F$COLOR_INACTIVE_MONITOR_FG}₸${F-}
            if [[ -z ${line#?} ]]; then
                essid+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} <disconnected> | %{B-}%{F-}"
            else
                essid+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} | %{B-}%{F-}"
            fi
            ;;
        W*)
            # bspwm's state
            wm=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        [ $num_mon -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                # monitor
                                FG=$COLOR_INACTIVE_MONITOR_FG
                                BG=$COLOR_INACTIVE_MONITOR_BG
                                ;;
                            M*)
                                # focused monitor
                                FG=$COLOR_FOCUSED_MONITOR_FG
                                BG=$COLOR_FOCUSED_MONITOR_BG
                                ;;
                        esac
                        wm="${wm} %{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-} "
                        ;;
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                ;;
                            F*)
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                BG=$COLOR_FOCUSED_FREE_BG
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                BG=$COLOR_OCCUPIED_BG
                                ;;
                            O*)
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_OCCUPIED_BG
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                BG=$COLOR_FOCUSED_URGENT_BG
                                ;;
                        esac
                        wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
                        ;;
                    # [LTG]*)
                    #     # layout, state and flags
                    #     wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
                    #     ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm}%{c}${title}%{r}${essid}${power}${battery0}${battery1}${volume}${layout}${clock}"
done
