#!/bin/bash

set -e

source $(dirname $0)/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        S*)
            # clock output
            clock=%{F$COLOR_INACTIVE_MONITOR_FG}⌚${F-}
            clock+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
            ;;
        T*)
            # xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            ;;
        V*)
            # volume output
            volume=%{F$COLOR_INACTIVE_MONITOR_FG}♪${F-}
            volume+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} | %{B-}%{F-}"
            ;;
        P*)
            # power output
            power=%{F$COLOR_INACTIVE_MONITOR_FG}⚡${F-}
            power+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} | %{B-}%{F-}"
            ;;
        B*)
            # battery output
            parsed_line=${line:2}
            bat_status=${parsed_line%" "*}
            bat_capacity=${parsed_line#*" "}
            if [[ ${line:1:1} == "0" ]]; then
                battery0="%{F$COLOR_INACTIVE_MONITOR_FG}Bat0${F-}"
                if [[ ${bat_status} == "Charging" ]]; then
                    battery0+="%{F$COLOR_POSITIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                elif [[ ${bat_status} == "Discharging" ]]; then
                    battery0+="%{F$COLOR_NEGATIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                else
                    battery0+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                fi
            elif [[ ${line:1:1} == "1" ]]; then
                battery1="%{F$COLOR_INACTIVE_MONITOR_FG}Bat0${F-}"
                if [[ ${bat_status} == "Charging" ]]; then
                    battery1+="%{F$COLOR_POSITIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                elif [[ ${bat_status} == "Discharging" ]]; then
                    battery1+="%{F$COLOR_NEGATIVE_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                else
                    battery1+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${bat_capacity}%{B-}%{F-} | "
                fi
            fi
            ;;
        E*)
            # essid output
            essid=%{F$COLOR_INACTIVE_MONITOR_FG}₸${F-}
            if [[ -z ${line#?} ]]; then
                essid+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} <disconnected> | %{B-}%{F-}"
            else
                essid+="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} | %{B-}%{F-}"
            fi
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [[ $# -gt 0 ]] ; do
                item=$1
                name=${item#?}
                case $item in
                    M*)
                        # active monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    m*)
                        # inactive monitor
                        if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
                        fi
                        ;;
                    O*)
                        # focused occupied desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
                        ;;
                    L*)
                        # layout
                        wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${essid}${power}${battery0}${battery1}${volume}${clock}"
done
