[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[theme.overrides]
separator = ""

[[block]]
block = "disk_space"
info_type = "available"
format = "$icon $used/$total (used) "

[[block]]
block = "net"
format = "$icon $ssid $signal_strength "
format_alt = "$icon $ssid $signal_strength $ip "
device = "wlan0"
if_command = "test -e /sys/class/net/wlan0"
[[block.click]]
button = "left"
cmd = "iwgtk"

[[block]]
block = "battery"
format = "$icon $percentage {$time}h $power"
device = "BAT0"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "battery"
format = "$icon $percentage {$time}h $power"
device = "BAT1"
if_command = "test -e /sys/class/power_supply/BAT1"

[[block]]
block = "temperature"
format = " $icon $max"
idle = 50
info = 70
warning = 85
{% if profile == "neo" %}
inputs = ["TSI0_TEMP"]
{% endif %}

[[block]]
block = "cpu"
format = "$icon CPU $utilization"
icons_format = " "

[[block]]
block = "memory"
format = "$icon MEM $mem_used_percents"
format_alt = "$icon MEM $swap_used_percents"
icons_format = " "

[[block]]
block = "sound"
format = "   $icon {$volume.bar(w:10, max_value:100)|Muted} "
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "ponymix toggle"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%F %R')"
icons_format = " "
