icons = "awesome"

[theme]
name = "gruvbox-dark"

[theme.overrides]
separator = ""

[[block]]
block = "disk_space"
info_type = "available"
unit = "GB"
format = "{icon} {used}/{total} ({available} free)"

[[block]]
block = "net"
format = "{ssid} {signal_strength}"
format_alt = "{ssid} {signal_strength} {ip}"
hide_missing = true
hide_inactive = true
device = "wlan0"

[[block]]
block = "battery"
format = "{percentage} {time}h {power}"
device = "BAT0"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "battery"
format = "{percentage} {time}h {power}"
device = "BAT1"
if_command = "test -e /sys/class/power_supply/BAT1"

[[block]]
block = "temperature"
collapsed = false
format = "{max}"
idle = 50
info = 70
warning = 80

[[block]]
block = "cpu"
format = "CPU {utilization}"
icons_format = " "

[[block]]
block = "memory"
display_type = "memory"
format_mem = "MEM {mem_used_percents}"
format_swap = "MEM {swap_used_percents}"
icons_format = " "

[[block]]
block = "sound"
format = "{volume} {volume:10#100}"
on_click = "ponymix toggle"
headphones_indicator = true

[[block]]
block = "time"
format = "%F %R"
icons_format = " "
