# Disabled as it's slightly annoying (see https://github.com/atuinsh/atuin/issues/2207)
#inline_height = 50

sync_address = "http://tank.bee-universe.ts.net:9841"
sync_frequency = "10m"
style = "compact"
show_preview = true
search_mode = "fulltext"
filter_mode_shell_up_key_binding = "session"
enter_accept = true

[sync]
records = true
