# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: ollama
clients:
- type: openai-compatible
  name: ollama
  api_base: http://neo.bee-universe.ts.net:11434/v1
  api_key: null
  models:
  - name: qwen3:30b
    max_input_tokens: 32768
