# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: ollama
clients:
- type: openai-compatible
  name: ollama
  api_base: http://morpheus.bee-universe.ts.net:11434/v1
  api_key: null
  models:
  - name: deepseek-r1:14b
    max_input_tokens: 10240
