export AWS_VAULT_BACKEND=pass
export AWS_VAULT_PASS_PREFIX=aws-vault
export AWS_SESSION_TOKEN_TTL=4h
export AWS_ASSUME_ROLE_TTL=4h
export AWS_FEDERATION_TOKEN_TTL=4h
export ANSIBLE_NOCOWS=1
export EDITOR=vim
export BROWSER=firefox
export LANG=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_MONETARY=de_DE.UTF-8
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export FZF_CTRL_R_OPTS=-s
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude node_modules'
export PATH=${PATH}:~/.cargo/bin:~/.yarn/bin:~/.pub-cache/bin:~/flutter/bin
export ADB_LIBUSB=1
