export AWS_VAULT_BACKEND=secret-service
export AWS_VAULT_SECRET_SERVICE_COLLECTION_NAME=login
export AWS_SESSION_TOKEN_TTL=4h
export AWS_ASSUME_ROLE_TTL=4h
export AWS_FEDERATION_TOKEN_TTL=4h

export EDITOR=vim
export BROWSER=firefox
export LESS="-R -i -M --use-color -DSky"

export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

export FZF_CTRL_R_OPTS=-s
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude node_modules'

export PATH=${PATH}:~/bin:~/.cargo/bin:~/.yarn/bin:~/.pub-cache/bin:~/src/flutter/bin:~/.local/share/android-sdk/cmdline-tools/latest/bin
export ADB_LIBUSB=1

# As per gpg-agent manpage
export GPG_TTY=$(tty)

# Make cross always use podman
export CROSS_CONTAINER_ENGINE=podman

# Android/Flutter stuff
export ANDROID_HOME=~/.local/share/android-sdk
export FLUTTER_HOME=~/src/flutter

# Misc exports
export DOOL_OPTS="--bytes"
